[package]
name = "voxa"
version = "0.7.1"
description = "Native low-latency P2P game streaming engine"
authors = ["Voxa"]
edition = "2021"

[lib]
name = "voxa_lib"
crate-type = ["rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "unstable"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-updater = "2.12.0"
tauri-plugin-process = "2.3.1"
getrandom = "0.3"
argon2 = "0.5"
tokio = { version = "1.47", features = ["net", "rt-multi-thread", "time", "macros"] }
voxa-native-core = { path = "native-core" }

[target.'cfg(windows)'.dependencies]
rusty-opus = "0.9.1"
windows-core = "0.61"
windows = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_System_ProcessStatus",
  "Win32_System_Threading",
  "Win32_System_Diagnostics_ToolHelp",
  "Win32_Graphics_Direct3D",
  "Win32_Graphics_Direct3D11",
  "Win32_Graphics_Gdi",
  "Win32_Graphics_Dxgi",
  "Win32_Graphics_Dxgi_Common",
  "Win32_Media_MediaFoundation",
  "Win32_Media_Audio",
  "Win32_Media_Multimedia",
  "Win32_System_Com",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_Variant",
  "Win32_UI_WindowsAndMessaging",
] }
