import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
const repo = process.env.GITHUB_REPOSITORY, tag = process.env.GITHUB_REF_NAME;
assert.match(tag ?? '', /^v\d+\.\d+\.\d+$/);
assert.match(repo ?? '', /^[\w.-]+\/[\w.-]+$/);
const gh = (...args) => execFileSync('gh', args, {encoding:'utf8'});
const current = JSON.parse(gh('api', `repos/${repo}/releases/tags/${tag}`));
assert.ok(current.assets.some(asset => asset.name === 'latest.json'), 'Sem manifesto de atualizacao');
assert.ok(current.assets.some(asset => /setup\.exe$/.test(asset.name)), 'Sem instalador');
const releases=JSON.parse(gh('api','--paginate','--slurp',`repos/${repo}/releases?per_page=100`)).flat();
const compare=(a,b)=>{const left=a.slice(1).split('.').map(Number),right=b.slice(1).split('.').map(Number);for(let i=0;i<3;i++){if(left[i]!==right[i])return left[i]-right[i];}return 0;};
const newer=releases.some(release=>!release.draft&&!release.prerelease&&/^v\d+\.\d+\.\d+$/.test(release.tag_name)&&compare(release.tag_name,tag)>0);
gh('api','--method','PATCH',`repos/${repo}/releases/${current.id}`,'-F','draft=false','-f',`make_latest=${newer?'false':'true'}`);
console.log(`${tag} publicado; latest=${!newer}`);
